# Generated by Django 2.1.5 on 2022-06-06 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FertConcern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MensePhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField(max_length=4100)),
                ('description', models.TextField(max_length=4100, null=True)),
                ('fert_concern', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.FertConcern')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Meal')),
                ('mense_phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipes.MensePhase')),
            ],
        ),
    ]
